### ISSUE TITLE
F-Droid link is not working

### ISSUE THREAD

**Issue by haripetrov** [nutritionfactsorg/daily-dozen-android#100]
Daily Dozen app is not listed in [F-Droid](https://f-droid.org/app/org.nutritionfacts.dailydozen). The link to the app in `README.md` is not working and I also cannot find the app using the search engine inside F-Droid.

**Comment by dimqua** [comment]
Should be listed soon.

https://gitlab.com/fdroid/fdroiddata/merge_requests/2746

**Comment by haripetrov** [comment]
Now the app is available: https://f-droid.org/packages/org.nutritionfacts.dailydozen
