### ISSUE TITLE
Explain what the app is about in the description

### ISSUE THREAD

**Issue by hoijui** [nutritionfactsorg/daily-dozen-android#103]
hello! :-)
i am a big fan of Mr. Greger, thanks for this!
I found the app on F-Droid, and the description there does NOT explain at all, what the app is actually about. It mentioned Dr. Gregers work, what he does, that he has a book, that his stuff is free, ...
the only thing i know about the app after reading the description, is that it does not contain ads, and it is free and open source. 
does it contain his book?
does it provide access to his videos?
does it tell me what to eat each day?

of course, i installed it, but i bet, not being a fan, i would certainly not have done it, as i have no idea what is inside.
keep it up, and thank you!
... now about to see what actually IS inside...

**Comment by vapurrmaid** [comment]
@hoijui  Are you referring to the description that exists on the download store?

**Comment by slavick** [comment]
Closing this issue as @vapurrmaid pointed out this information already exists.
