### ISSUE TITLE
Daily Dozen Challenge

### ISSUE THREAD

**Issue by digilou** [nutritionfactsorg/daily-dozen-android#104]
I suggested this feature for IOS (my current device of choice), but I think it would be great for Android users, too.

> I just saw the video Dr. Gregor put out for the Daily Dozen challenge.
> 
> Idea: add some sort of competition with friends feature and share stats and challenges with each other. Facebook and Google authorization. Access to contact list to invite others to join through app without Facebook or Google account. Possible Fitbit API integration?

https://github.com/nutritionfactsorg/daily-dozen-ios/issues/23

**Comment by slavick** [comment]
Thank you for your suggestion. This is currently outside the scope of what we are looking to do with the app at this time.
