### ISSUE TITLE
Cucumber is not on this app at all.

### ISSUE THREAD

**Issue by BenjMonast** [nutritionfactsorg/daily-dozen-android#105]
I don't know if this is a bug or a feature, but I can't find cucumber under any of the categories.

**Comment by andrijeski** [comment]
I don't think there's anything valuable in a cucumber from nutritional perspective. Therefore it is not in the list.

**Comment by alibitek** [comment]
Indeed, https://en.wikipedia.org/wiki/Cucumber#Nutrition says: "In a 100-gram serving, **raw cucumber (with peel)** is 95% water, provides 67 kilojoules (16 kilocalories) and supplies low content of essential nutrients, as it is notable only for vitamin K at 16% of the Daily Value (table)."

**Comment by slavick** [comment]
I'm closing this issue because Cucumber is not listed in Dr. Greger's book and therefore should not be included in the app.
