### ISSUE TITLE
Inertial Scrolling

### ISSUE THREAD

**Issue by msbeck** [nutritionfactsorg/daily-dozen-android#106]
As a user, when I scroll up quickly and let go, I'd like for a long list of items to continue scrolling with inertia rather than stop immediately when I pick my finger up. 

It currently doesn't do that in the lists of food under a category on Android at least.

**Comment by msbeck** [comment]
It works if you start the scroll on the gap between the servings size box and the types box, but not if you start the scroll by touching within them.

**Comment by DJ-Tai** [comment]
I believe I have found a solution for this. I don't see a develop branch though - should I just fork this, create a develop branch, and submit a pull request?

**Comment by alibitek** [comment]
@DJ-Tai You can start working from the master branch. The develop branch will probably be created by @slavick when you are ready to submit your pull request.

**Comment by slavick** [comment]
Closing this issue as it has been fixed in the v16 branch
