### ISSUE TITLE
persian translation 

### ISSUE THREAD

**Issue by alighamari** [nutritionfactsorg/daily-dozen-android#109]
hello,
please add Persian to your app.
if you need, I can translate strings and send them to you as soon as possible

**Comment by slavick** [comment]
Hi @alighamari,

I would be happy to include a Persian translation of the app. If you would like to translate the strings, you can use the merged PRs that added translations in other languages as a reference. Here's a link to the Italian translation: https://github.com/nutritionfactsorg/daily-dozen-android/pull/98

Thanks
