### ISSUE TITLE
B12 & Vitamin D

### ISSUE THREAD

**Issue by jpritikin** [nutritionfactsorg/daily-dozen-android#11]
These supplements should not be overlooked and should be mentioned explicitly.

**Comment by haripetrov** [comment]
I have the same opinion about this question. This is very important for everyone.

**Comment by christirichards** [comment]
@jpritikin @slavick @haripetrov Where in the app do you think it would make the most sense to include these, as I agree they should be mentioned somewhere?  Including a mention in the menu, however, doesn't seem like it would gain the most visibility and I'm afraid it would be overlooked.

**Comment by haripetrov** [comment]
You can put one general subcategory called "Vitamins" (in the same way as Exercises). In side this category we can have detailed information about vitamin d, vitamin B12.

**Comment by jpritikin** [comment]
I guess mention of Omega-3 and iodine could go here too. Most people get iodine via salt, but if you decide to go with sea vegetables, then that's something you need to remember to eat.

**Comment by chrisbryant** [comment]
It's a good idea though I feel there needs to be a balanced approach. You wouldn't want people to think that they need to take typical vitamin "supplements" when they are on a WFPBD. Thanks for all your work on the app, it's great!

**Comment by haripetrov** [comment]
This is exception. These vitamins are very important and since most people are not aware of them (when they are changing their diet) this can lead to very serious health problems. In order to avoid this situation I think that we have to have additional category for Vitamins which cannot be obtained from food.

**Comment by MovGP0** [comment]
@jpritikin I don't think that Ω-3 fatty acids and iodine need to be substituted, when sticking to this diet. Nuts will provide you with more than enough Ω-3 fatty acids. And with iodine it is much more likely that you get too much of it than too less.

**Comment by MovGP0** [comment]
@christirichards i guess the `MainActivity` seems to be the right place for this. just handle it like all the other food items. 

However, some users might want to disable those in the settings,which would require a `SettingsActivity`. The current `DailyReminderSettingsActivity` could become part of that new activity.

**Comment by slavick** [comment]
This has been added in v14.
