### ISSUE TITLE
Filter unavailable/allergic plants -feature request

### ISSUE THREAD

**Issue by senpl** [nutritionfactsorg/daily-dozen-android#111]
Currently app shows many plants/elements that could not be available in current country. They should be option to not show them. It should help people with allergies.

**Comment by christirichards** [comment]
This is not functionality we are looking to add to the app at this time. The Daily Dozen app provides lists of suggested foods to illustrate the types of foods that can be eaten in each category. This is not a hard rule on what foods you must eat. If you have a food allergy to a certain food, then simply do not eat it.
