### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by Shaikailash** [nutritionfactsorg/daily-dozen-android#116]
Hi, It should be fairly easy to provide translation for other languages, as there is not much text in the app. Could you provide guidance on how we can contribute?
I am glad to contribute by translating it into Italian (my mother tongue).
Best,

**Comment by Armfoot** [comment]
Hi Shaikailash, the Italian translation has already been provided 10 months ago (it's simply a _strings.xml_ file), as you can read here:
https://github.com/nutritionfactsorg/daily-dozen-android/pull/98

I also contributed Portuguese translations a while ago, and it may take a longer time until they get live. If you want to review the Italian ones reference that pull request above.

**Comment by Shaikailash** [comment]
Hi

I would like to propose some edits to the Italiantranslation. I have an 
account on GitHub but I don't understand how I can edit the file.

Best,
Stefano

Il 24.11.2018 16:55, Armfoot ha scritto:
