### ISSUE TITLE
Ability to adjust recommendations

### ISSUE THREAD

**Issue by phrakture** [nutritionfactsorg/daily-dozen-android#126]
I know this may go against the spirit of the app, but I'd really like the ability to adjust the recs for personal preference. Maybe add a serving of beans or nuts or something like that.

It'd be extra nice if I could add my own items to be tracked! Maybe I want to make sure I specifically eat 2 servings of carrots or something...

**Comment by christirichards** [comment]
This is not something we are looking to include in the app right now.  The Daily Dozen is a set of guidelines rather than a hard rule of what you should be eating each day.
