### ISSUE TITLE
Vitamin D no longer visible

### ISSUE THREAD

**Issue by nozone** [nutritionfactsorg/daily-dozen-android#129]
Was it intentional to replace Vitamin D with Omega 3?

**Comment by nozone** [comment]
I see now that it was intentionally removed in this commit -- https://github.com/nutritionfactsorg/daily-dozen-android/commit/89d6de0b9c075d663b942196a9a9ae88a4c0e8d8

Whats the reason for this?

**Comment by imtezcan** [comment]
Was this a decision based on science? or just convenience?
curious now that the vitamin d option and all history in the app is inaccessible

**Comment by vgstef** [comment]
I'm also opposed to the removal of the D vitamin.  Here in Canada, we need D vitamin supplements during half of the year. 

But even where people get enough sunlight, people need to get out in the sun!

So my suggestion is to bring back the Vitamin D with one tick box and the explanation : "You need to get a supplement or get sun exposure."

**Comment by christirichards** [comment]
Per Dr. Greger’s recommendation, Vitamin D was removed considering not everyone needs it, just those not getting adequate sun exposure as explained here: http://nutritionfacts.org/topics/vitamin-d and our formal recommendations here: https://nutritionfacts.org/2011/09/12/dr-gregers-2011-optimum-nutrition-recommendations/
