### ISSUE TITLE
v16 breaks F-Droid builds

### ISSUE THREAD

**Issue by duxovni** [nutritionfactsorg/daily-dozen-android#130]
The addition of Firebase Analytics in v16 seems to be preventing F-Droid from building the new version: https://f-droid.org/wiki/page/org.nutritionfacts.dailydozen/lastbuild

It also looks like the snippet that makes the inclusion of Crashlytics only apply to the Play Store build flavor got removed in 89d6de0?

**Comment by c64bob** [comment]
This seems to have been fixed.
https://f-droid.org/de/packages/org.nutritionfacts.dailydozen/
