### ISSUE TITLE
New item "Plant-based Omega 3s" left untranslated

### ISSUE THREAD

**Issue by qyearsley** [nutritionfactsorg/daily-dozen-android#131]
In v16 (https://github.com/nutritionfactsorg/daily-dozen-android/commit/89d6de0b9c075d663b942196a9a9ae88a4c0e8d8) the string omega3 is left as "Plant-based Omega 3s" in most/all languages, which doesn't look good in all languages other than English.

Perhaps as a quick pass, even without official auditing by speakers of each language, we could run this string phrase through Google Translate or something?

**Comment by slavick** [comment]
This is a good suggestion and I will be doing this from now on.

**Comment by qyearsley** [comment]
Thanks
