### ISSUE TITLE
Where is the `develop` branch?

### ISSUE THREAD

**Issue by ingochris** [nutritionfactsorg/daily-dozen-android#133]
Is it just me or is the repo only showing `master`?

```
ingochris@deathstar:/tmp/github/nutritionfactsorg/daily-dozen-android$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
```

```
Please submit all pull requests to the nutritionfactsorg/daily-dozen-android repository in the develop branch.
```
Source: https://github.com/nutritionfactsorg/daily-dozen-android/blob/master/CONTRIBUTING.md

I couldn't figure it out, so I opened my PR to master branch in the meantime.

**Comment by caugner** [comment]
It looks like:

1. the `CONTRIBUTING.md` falsely references the (non-existing) `develop` branch instead of the `master` branch.
2. the repository is not up-to-date (`v16` vs `v17` in the Play Store).

@slavick Can you confirm this?

**Comment by slavick** [comment]
I've created the `develop` branch and `master` has been updated with the latest code and `v17` tag.
