### ISSUE TITLE
include some note as to why brown rice is not included in whole grains

### ISSUE THREAD

**Issue by myusrn** [nutritionfactsorg/daily-dozen-android#135]
when i visit https://github.com/nutritionfactsorg/daily-dozen-android/issues/60 it suggest that long grain [ and regular ] brown rice was removed from whole grains due to some arsenic contamination matter that arose back in 2017. 

Should the app find a way to introduce a note in the whole grains more info view that points people to a couple of key nutritionfacts.org videos outlining why its not in the list, e.g. https://nutritionfacts.org/video/do-the-pros-of-brown-rice-outweigh-the-cons-of-arsenic/ and https://nutritionfacts.org/video/where-does-the-arsenic-in-rice-mushrooms-and-wine-come-from/.  In the latter video i might deduce that organic long grain brown rice not fertilized with chicken or livestock waste wouldn't have as much or if any arsenic. 

The note could help others who like myself under the impression that morning oatmeal and evening long grain brown rice creates a simple way to get ones daily whole grains intake.

**Comment by jpritikin** [comment]
Maybe color could be used to signal this kind of negative recommendation?

**Comment by myusrn** [comment]
Sure like a yellow / caution for the font text and hyperlink to whatever nutritionfacts.org blog or video best explains why.  Watching the two videos above and others, all from the fall 2017 time frame, it wasn't entirely clear to me if organic long grain brain rice is still a concern.  

Since it like oatmeal is such an easy way to get whole grain input it would be good to clarify in the app if we should be avoiding what i think many would just be assuming is okay.  

I ended up poking around in the info sections of other daily checklist line items to see if i was just mistaken thinking it was a whole grain and was instead listed under another category.  When i didn't find it elsewhere that's when i went looking for why in the github issues history and nutritionfacts.org search results.

**Comment by myusrn** [comment]
. . . also i just came back from my local grocery store and noticed all the bulk and packaged brown rice offerings have the 'non-gmo' logo on them.  Watching dr. greger videos its stated that only rice modified to be arsenic resistant can survive being grown in the south east regions and and elsewhere where the arsenic levels in the soil are high.  So shouldn't this mean that rice can be included in the whole grains sections more info view with asterics clarifying that it needs to be non-gmo certified for the reasons discussed in the https://nutritionfacts.org/topics/rice videos?

**Comment by caugner** [comment]
It appears that the arsenic content of whole grain rice varies a lot.

For example [in this video](https://www.youtube.com/watch?v=FWyv7lgJAK0&t=34s), the Austrian nutrition expert Niko Rittenau recently described that he requested analyses from several producers of whole grain rice sold in Germany and none of them contained any arsenic.

**Comment by myusrn** [comment]
If organic non-gmo long grain brown rice is not in fact afflicted with the arsenic problem that is present in other rice crops then its a shame to not have it in daily dozen given rice cooker prepared long grain brown rice with dried black beans mixed in makes for a very tasty base on to of which to load up other vegetables, nuts and seasonings detailed in daily dozen app.

**Comment by jpritikin** [comment]
> Austrian nutrition expert Niko Rittenau recently described that he requested analyses from several producers of whole grain rice sold in Germany and none of them contained any arsenic.

I don't consider this very strong evidence. I'd like to see numbers published in a peer reviewed publication.

> If organic non-gmo long grain brown rice is not in fact afflicted with the arsenic problem

Unfortunately it is. For example, https://www.lundberg.com/info/arsenic-in-food/product-faq/

I urge people to try other grains. For example, I enjoy 50/50 mix of steel cut oats and millet. Try it out!

**Comment by caugner** [comment]
@jpritikin 

> I don't consider this very strong evidence. I'd like to see numbers published in a peer reviewed publication.

Can you provide evidence from a peer reviewed publication that arsenic is a wide-spread problem in organic wholegrain rice across producers?

**Comment by rkraneis** [comment]
Well, [this relatively current report](https://www1.wdr.de/verbraucher/ernaehrung/reis-labortest-102.html) by a German public-service broadcaster asks consumers to not eat brown rice on a daily basis.

**Comment by rkraneis** [comment]
Another [report](https://www.foodwatch.org/de/informieren/arsen-in-reis/arsen-in-baby-reisprodukten/) by a German consumer rights organization with links to actual reports for rice based baby meals.

**Comment by rkraneis** [comment]
The important thing to note here is that we are not talking about _contamination_ but about the fact that rice naturally retains more arsenic and that there is no _safe level_ for arsenic consumption. I myself still do eat brown rice. But I don't think it should be recommended when safe alternatives exist.

**Comment by jpritikin** [comment]
> Can you provide evidence from a peer reviewed publication that arsenic is a wide-spread problem in organic wholegrain rice across producers?

I provided a link to Lundberg's website, an organic rice producer that published their own arsenic measurements. Yes, these numbers are high. Also see https://www.ewg.org/foodscores/content/arsenic-contamination-in-rice
