### ISSUE TITLE
Meta: Repository Workflow

### ISSUE THREAD

**Issue by caugner** [nutritionfactsorg/daily-dozen-android#143]
I have a couple of questions about this repository:

1. What's the reason that this repository is not always up to date? Is there another Git server where development mainly happens?
2. What's the intended difference between `develop` and `master` (right now they are the same)?
3. Is there a roadmap?
4. How is the app currently built and published to Play Store/F-Droid?
5. Where can I find in instructions on how to build the app myself?

**Comment by slavick** [comment]
1. The previous update was developed outside of GitHub as it contained information from the new book that had not been released at that point.
1. `master` reflects what has been released on the Play Store and `develop` is for active development going forward.
1. We do not have a roadmap currently.
1. I am manually creating the apk and uploading it to the Play Store.
1. All you should have to do is clone this repository and open the directory in Android Studio. It will then prompt you to install the proper SDK and from there you should be able to run the app on your phone or the emulator.

I'm going to close this issue now, but please reopen if you have any other questions.
