### ISSUE TITLE
German translation for "Optimierungen -> Jede Nacht -> Schnell nach 19:00" wrong

### ISSUE THREAD

**Issue by jsplate** [nutritionfactsorg/daily-dozen-android#144]
Instead of "Schnell nach 19;00" the correct german translation should be "Fasten nach 19:00".

Grammatically better would be "Fasten Sie nach 19:00" because in the other items the you- form of address is used.

**Comment by slavick** [comment]
This has been addressed by one of our translators in our latest release. Thanks!
