### ISSUE TITLE
Backup restoration

### ISSUE THREAD

**Issue by regagain** [nutritionfactsorg/daily-dozen-android#147]
Hi!

What's the procedure for restoring a backup?

**Comment by dipujd** [comment]
Hi, I am wondering the same. 

I have found a RestoreTask feature on the backend ( https://github.com/nutritionfactsorg/daily-dozen-android/blob/master/app/src/main/java/org/nutritionfacts/dailydozen/task/RestoreTask.java )

However, I don't see a menu item on the frontend that connects with the restore task.

**Comment by dipujd** [comment]
Hi, I am wondering the same.

I have found a RestoreTask feature on the backend ( https://github.com/nutritionfactsorg/daily-dozen-android/blob/master/app/src/main/java/org/nutritionfacts/dailydozen/task/RestoreTask.java )

However, I don't see a menu item on the frontend that connects with the restore task: https://github.com/nutritionfactsorg/daily-dozen-android/blob/master/app/src/main/java/org/nutritionfacts/dailydozen/activity/MainActivity.java

**Comment by slavick** [comment]
Here's a short clip of how to restore a backup file. It's using an older version of the app, but the process is the same.

[DailyDozen - How to Restore from Backup](https://www.youtube.com/watch?v=nY9_Qzx_Vnw)

**Comment by dipujd** [comment]
It worked on the newest version too. Thanks for your help @slavick 👌
