### ISSUE TITLE
Make translation user-friendly

### ISSUE THREAD

**Issue by 12people** [nutritionfactsorg/daily-dozen-android#148]
There are translation platforms out there that host open-source projects for free. For example, [Transifex](https://docs.transifex.com/projects/open-source-project) or [Weblate[(https://hosted.weblate.org/).

For those less technically inclined (installing git, cloning a repo, and submitting a pull request are quite technical things that not everyone would be willing to do), a web service like this would make it much easier to contribute with translations.

**Comment by slavick** [comment]
You make a good point, but NutritionFacts.org has partnered with official translators going forward. I cannot verify the correctness of languages other than English so we will be relying exclusively on the official translations.
