### ISSUE TITLE
Adaptive icon

### ISSUE THREAD

**Issue by 12people** [nutritionfactsorg/daily-dozen-android#149]
New versions of Android recommend creating adaptive app icons: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive .

I'd like to make one for Daily Dozen. However, I would need the SVG of the current icon. Is it available anywhere? Could it be shared?

**Comment by slavick** [comment]
Closing this as the icon has been made adaptive in the latest release: https://github.com/nutritionfactsorg/daily-dozen-android/pull/158
