### ISSUE TITLE
Berries Serving Noted as 2 on website, but 1 in app

### ISSUE THREAD

**Issue by auerbachb** [nutritionfactsorg/daily-dozen-android#155]
Saw this on 2020.08.08 on the page https://nutritionfacts.org/topics/daily-dozen/

**Comment by slavick** [comment]
This is almost certainly a mistake with the article. The app matches what is printed in the How Not to Die book, as well as the [daily dozen t-shirt](https://drgreger.org/collections/swag/products/daily-dozen-unisex-t-shirt), and [daily dozen checklist video](https://nutritionfacts.org/video/dr-gregers-daily-dozen-checklist/).
