### ISSUE TITLE
Keep track of food type

### ISSUE THREAD

**Issue by afarntrog** [nutritionfactsorg/daily-dozen-android#159]
Hi y'all,

I plan on working on the following feature for myself. Please advise if this is something you would be interested in adding to the project.

When a user "checks" a serving they would then select and save the `Food Type` as well. For example if I check `Beans` I would then select one of the 17 `Bean types` listed. This is great for record purposes to see what I consumed in the past. When I go to an earlier date I can see not only what Food category was consumed but also which food type.

Is this something that you would consider adding to the app?

Thanks for working on this project.

**Comment by christirichards** [comment]
Thank you for your suggestion. This is currently outside the scope of what we are looking to do with the app at this time.
