### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [nutritionfactsorg/daily-dozen-android#161]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by christirichards** [comment]
If someone would like to take this on, go for it.  Otherwise, it's not on our radar to actively support F-Droid builds at this time.
