### ISSUE TITLE
App crashes when I add an item to: food_info_serving_sizes_beans

### ISSUE THREAD

**Issue by petarvasilev91** [nutritionfactsorg/daily-dozen-android#162]
Hi, I am trying for fork and edit the app and currently I am trying to figure out how to change some of the stuff. So, I found the strings.xml file with all the data and I tried changing this:

    <string-array name="food_info_serving_sizes_beans">
        <item>%s of hummus or bean dip</item>
        <item>%s cooked beans, split peas, lentils, tofu, or tempeh</item>
        <item>%s of fresh peas or sprouted lentils</item>
    </string-array>

to this: 

    <string-array name="food_info_serving_sizes_beans">
        <item>%s of hummus or bean dip</item>
        <item>%s cooked beans, split peas, lentils, tofu, or tempeh</item>
        <item>%s of fresh peas or sprouted lentils</item>
        <item>this is a test</item>
    </string-array>

but that seems to crash the app on my Samsung A9 phone. When I reverted back it started working again. I guess it was some logical error.

Any ideas appreciated!

**Comment by christirichards** [comment]
Unfortunately, you will need to seek out support elsewhere for forking and modifying your own version of the app. We need to keep the issues on here strictly related to Dr. Greger's Daily Dozen. Thank you for understanding!
