### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by petarvasilev91** [nutritionfactsorg/daily-dozen-android#163]
Hi, I am trying to fork the app and edit but I am very new to Android development. Can you point me in the direction which would allow me to add/remove from the daily dozen and 21 tweaks lists? I've been looking at the code but I haven't figured it out yet.

**Comment by senpl** [comment]
Describe more precisely to what and to what you want to change.

**Comment by petarvasilev91** [comment]
Like I said before, I am trying to add and remove items (e.g. foods) from the daily dozen list, and the same for the 21 tweaks list.

**Comment by christirichards** [comment]
> Hi, I am trying to fork the app and edit but I am very new to Android development. Can you point me in the direction which would allow me to add/remove from the daily dozen and 21 tweaks lists? I've been looking at the code but I haven't figured it out yet.

Unfortunately, you will need to seek out support elsewhere for forking and modifying your own version of the app. We need to keep the issues on here strictly related to Dr. Greger's Daily Dozen. Thank you for understanding!
