### ISSUE TITLE
Integrate with Cronometer

### ISSUE THREAD

**Issue by EnricGTorrents** [nutritionfactsorg/daily-dozen-android#165]
Is there any way items in the Daily Dozen checklist could be automatically checked using data pulled from Cronometer? They don't offer an API to the public, but I have seen websites like nutrientoptimiser.com that are able to connect with Cronometer and pull data from it. My coding experience is very limited (basically only R and some Python), but I would be happy to help to the best of my abilities if there is interest in adding this feature.

**Comment by slavick** [comment]
Thank you for your suggestion. This is currently outside the scope of what we are looking to do with the app at this time.
