### ISSUE TITLE
Link to "mesclun mix" is broken

### ISSUE THREAD

**Issue by tabasco-flame** [nutritionfactsorg/daily-dozen-android#175]
Under Greens, if I click on the VIDEOS button next to Mesclun mix (assorted young salad greens), it takes me to the "Not Found" page on NutritionFacts.org.

I looked for "mesclun mix" and "spring greens", and no longer find these direct topics at the website.

**Comment by slavick** [comment]
Thank you, this will be fixed in the next release.
