### ISSUE TITLE
Consider update to link for "Concord Grapes"

### ISSUE THREAD

**Issue by tabasco-flame** [nutritionfactsorg/daily-dozen-android#176]
Under Berries, if I click on the VIDEOS button next to Concord Grapes, it takes me to the Concord Grapes page on NutritionFacts.org. However, this page has no information, and displays the message "Sorry, no results were found." under the Concord Grapes title.

A better link might be to the Grapes topic (https://nutritionfacts.org/topics/grapes/) which includes references to Concord Grapes (see last sentence, for example).

**Comment by slavick** [comment]
Thank you, this will be fixed in the next release.
