### ISSUE TITLE
Consider update to "Beet greens" link

### ISSUE THREAD

**Issue by tabasco-flame** [nutritionfactsorg/daily-dozen-android#182]
Under Greens, if I click on the VIDEOS button next to Beet greens, it takes me to the "Not Found" page on NutritionFacts.org. However, beet greens are discussed under the beets topic (https://nutritionfacts.org/topics/beets/), and the video links there include information on both beets and beet greens.

Consider updating the Beet greens link to the Beets topic.

**Comment by slavick** [comment]
Thank you, this will be fixed in the next release.
