### ISSUE TITLE
Consider update to "Purple potatoes" link

### ISSUE THREAD

**Issue by tabasco-flame** [nutritionfactsorg/daily-dozen-android#183]
Under Other Vegetables, if I click on the VIDEOS button next to Purple potatoes, it takes me to the "Not Found" page on NutritionFacts.org. However, there are several references to purple potatoes in the potatoes topic (https://nutritionfacts.org/topics/potatoes/).

Consider updating the Purple potatoes link to the Potatoes topic.

**Comment by slavick** [comment]
Thank you, this will be fixed in the next release.
