### ISSUE TITLE
Consider adding link for Peppermint tea

### ISSUE THREAD

**Issue by tabasco-flame** [nutritionfactsorg/daily-dozen-android#191]
Under Beverages, there is no VIDEOS button next to Peppermint tea. Consider adding a link to the peppermint topic (https://nutritionfacts.org/topics/peppermint/). It mentions peppermint tea. There are also video links there that discuss peppermint tea. In addition, a precedent is set with Lemon balm tea linking to the Lemon Balm topic, for example.

**Comment by slavick** [comment]
Thank you, this will be fixed in the next release.
