### ISSUE TITLE
Learning android app game

### ISSUE THREAD

**Issue by eminem0091** [nutritionfactsorg/daily-dozen-android#194]
Hello guys,

Maybe its good or bad idea but... What about "Learning food app game" app for andorid?

In this app can be from easiest questions like "Select healthy and unhealty foods" to hardest "Select food what causing cancer".

Point of this app is teach tons of informations in short time because I thing best way to learn thing is by the games :) 

![](https://i.imgur.com/MgnGmeQ.png)

Source of information will be Michael Greger videos because "In Nutritionfacts.org we trust".

Also every question can have link to source video from youtube Nutritionfacts.org.

Also spending time with watching everyday videos is not best time efficient because if "Nutritionfacts.org Youtube" have 2000+ videos and for example every video have 10 minutes then its like 333 hours. If someone can spend only 1 hour a day then its 333 days to look on all videos... :( Also lot of informations (50% Cone of learning) can be forgotten.

Etc...

What do you think? :)

**Comment by paperclipmaximizer** [comment]
I don't think it fits the specific purpose of dailydozen app. However, I think **this is a great idea for an anki deck**. I would personally use it and I'm sure others would too.

See ankiweb.net/

**Comment by slavick** [comment]
Sounds like an idea for a separate app. Closing this issue.
