### ISSUE TITLE
Feature Request: have TWEAKS and DAILY DOZEN show the same date

### ISSUE THREAD

**Issue by yetihk** [nutritionfactsorg/daily-dozen-android#195]
When I switch from TWEAKS to DAILY DOZEN while fillout out yesterday, it switches to today instead of staying on that day I was filling out

**Comment by marc-medley** [comment]
@yetihk Thanks for your input.

As currently implemented, the dates for "Daily Dozen" and "21 Tweaks" pages are set independently. What appears to be a _"switches to today" by the software_ situation is really a case of the other _tab has not yet been set by the user to yesterday_.

That said, the user experience could be streamlined by having the same date show on both tab views, as you noted. I will see if this improvement is reasonable to implement.

**Comment by yetihk** [comment]
Appreciate the fast reply and for considering this request. In the last
couple of weeks I've accidentally entered a whole day to realize it was for
today not yesterday. Apart from that, truly great (and helpful) app!

**Comment by marc-medley** [comment]
@yetihk I'm rewriting my comments a bit. I work on the iOS Daily Dozen software. @slavick works on the Android software. I had submitted the previous comment before I realized that I was posting on an Android issue.

_The iOS app also has independent dates for the "Daily Dozen" and "21 Tweaks" views._

My first answer was from the iOS viewpoint. Here's what I noted before...

> As currently implemented, the dates for "Daily Dozen" and "21 Tweaks" pages are set independently. What appears to be a _"switches to today" by the software_ situation is really a case of the other _tab has not yet been set by the user to yesterday_.
> 
> That said, the user experience could be streamlined by having the same date show on both tab views, as you noted. I will see if this improvement is reasonable to implement.

What is you've observed and reported is part of the current implementation "as-is". (In other words, it's not technically broken code.) And, I've noted the same speed bump when inputting data myself. However, I know the software behavior, so I don't thing anything of setting the dates independently.

At the point, please consider this as feature enhanced request pending internal review. Thanks.

**Comment by slavick** [comment]
@yetihk Thank you for pointing out this annoying behavior, I have experienced it as well. Now that there's two of us, I went ahead and made the fix. It will go out in the next release. Here's the commit if you're interested: https://github.com/nutritionfactsorg/daily-dozen-android/commit/fed37f1b5fddf7e088e7bc4429c455576e0d5def

**Comment by yetihk** [comment]
Thanks, that will be a really good improvement.

Off topic - in my work I'm a mobile UX / PM and also vegan/WFPB. So am
happy to help with beta testing, feedback or any other (eg copywriting for
the appstore, a/b testing to increase downloads etcetc)
