### ISSUE TITLE
Translations: German, Hebrew, Portuguese, Russian

### ISSUE THREAD

**Issue by marc-medley** [nutritionfactsorg/daily-dozen-android#197]
@slavick The attached `android-resources.zip` file contains Nutrition Facts `strings.xml` translations for Hebrew, Portuguese, Portuguese (Brazil), Portuguese (Portugal) and Russian.

[android-resources.zip](https://github.com/nutritionfactsorg/daily-dozen-android/files/7553559/android-resources.zip)

Please check if these files work OK with the Android software. Let me know if anything is missing, incomplete or broken. See details below.

Also, if the Android app builds OK with these xml files, would it be possible to provide a test (non-general-release) build for the translators to review?

Thanks.

## Details

The files are also located here:

* [English_US](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/English_US/android/values/strings.xml)
* [Hebrew](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Hebrew/android/values-he/strings.xml)
* [Portuguese](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Portuguese/android/values-pt/strings.xml)
* [Portuguese_Brazil](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Portuguese_Brazil/android/values-pt-BR/strings.xml)
* [Portuguese_Portugal](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Portuguese_Portugal/android/values-pt-PT/strings.xml)
* [Russian](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/Russian/android/values-ru/strings.xml)

The files were programmatically generated from the TSV files provided from the translation team. _There were no subsequent hands edits done to the `strings.xml` files._

The translated `strings.xml` is created by mapping the Android keys from the translated TSV file to overwrite values of an in-memory copy of the English_US `strings.xml`

A (re-generated) English_US `strings.xml` is also include to give an idea of how the formatting is affected through the process.

The English_US `strings.xml` file is used as the base reference to provide the following:

* Preserves key ordering.
* Preserves most whitespace as needed for readability.
    * `<item />` may have the form `<item/>` or `<item></item>`
* Provides consistent formatting across the languages.
* Diff-able structure standard developer text-based tools.  (i.e. diff tool does not need to be specifically xml aware)
* Allows for a consistency check that the same keywords are being used across the languages.

**Observations: Things to Check**

_An effort was made to use the same translated text for both Android and iPhone where possible. There may be some unexpected issues which need to be addressed._

* [Typographic quotations](https://en.wikipedia.org/wiki/Quotation_marks_in_English) are used.  This avoids the need for `\'` escaped programmer style quotation characters in the text body.
* `activity_welcome_text` is longer than what is on the main branch. Was this shortened for the Android release based on space constraints?
* **carriage returns** Check that text with `\n` carriage returns work OK for Android.
* **string argument index** A `$` argument index is present in the current main release branch for `format_version` and `format_num_days`. Would it be reasonable to adjust the Android java code to not need the argument index in the translation string? If yes, then the same translation TSV row can be used for both Android and iPhone.

_prior version_

``` xml
<string name="format_version" formatted="false">version %s</string>
<string name="format_num_days" formatted="false">%d days</string>
```

_current branch_

``` xml
<string name="format_version">version %1$s</string>
<string name="format_num_days">%1$d days</string>
```

* `%s` strings are programmatically generated base on a string differencing algorithm the corresponding imperial and metric TSV rows. Basically, two imperial/metric TSV rows (equivalent to two imperial/metric iPhone JSON entries) maps to three `<item>`s in Android. This may look different than expected in the xml; however, the parts should combine correctly in the running application code.

For example:

``` xml
<string-array name="food_info_serving_sizes_other_fruits">
    <item>%s1 medium-sized fruit</item>
    <item>1%s cut-up fruit</item>
    <item>%s dried fruit</item>
</string-array>
<string-array name="food_info_serving_sizes_other_fruits_imperial">
    <item></item>
    <item> cup</item>
    <item>¼ cup</item>
</string-array>
<string-array name="food_info_serving_sizes_other_fruits_metric">
    <item></item>
    <item>20 g</item>
    <item>40 g</item>
</string-array>
```

**Comment by slavick** [comment]
@marc-medley Thank you Marc, I will create apks for the testers in the coming days.

**Comment by marc-medley** [comment]
@slavick A German translation which has been reviewed, updated and supports both platforms has been added. The Brazilian Portuguese has been updated for the region.

The attached `android-resources-de-en-he-pt-ru.zip` file:

* Adds German
* Regionalized Brazilian Portuguese
* Some minor changes to other languages due to updated data processing flow.
* Extra intermediate files are removed (e.g. `keysExpectedXml*.txt`)

Android XML resource files: [android-resources-de-en-he-pt-ru.zip](https://github.com/nutritionfactsorg/daily-dozen-android/files/7630633/android-resources-de-en-he-pt-ru.zip)

Please let me know if you find any issues with the set. Thanks.

**Comment by andras-gyarmati** [comment]
Hi, I can help with hungarian translation if you are interested. Let me know

**Comment by marc-medley** [comment]
Translations are now being provided via Pull Requests, so this issue no longer needs to be open.
