### ISSUE TITLE
German translation has translation only on main themes, not items - those remain all english

### ISSUE THREAD

**Issue by marc-medley** [nutritionfactsorg/daily-dozen-android#215]
Observation below provided by @Lbouska from [Czech translation testing](https://github.com/nutritionfactsorg/daily-dozen-localization/issues/26#issuecomment-1334989534).

> German translation has translation only on main themes, not items - those remain all english.

What is the information for the above mentioned scenario:

test device hardware model?
test device operating system version?
Daily Dozen about-this-app version?

> german without items:
> What is the information for the above mentioned scenario:
> test device hardware model? Samsung A53, Samsung A51
> test device operating system version? Android 13, Andriod 12
> Daily Dozen about-this-app version? current from google play 21.3

@slavick Note the issue being reported for the currently released 21.3

@Lbouska Some more questions:

1. Is German OK the the beta release (22 - beta)?
2. Was the app terminated and restarted when languages was change? Do you have any more information which would help to reproduce the scenario?

**Comment by marc-medley** [comment]
Update: ["German translation on iPhone is now fully OK!"](https://github.com/nutritionfactsorg/daily-dozen-localization/issues/26#issuecomment-1344071745)

**Comment by slavick** [comment]
I was able to recreate this issue by not killing the app when changing the language in the system settings. Killing the app and reopening it fixes the issue. I'll try to see if there is a way to refresh the app without restarting it.

**Comment by Edaryion** [comment]
> Update: ["German translation on iPhone is now fully OK!"](https://github.com/nutritionfactsorg/daily-dozen-localization/issues/26#issuecomment-1344071745)

Sehr gut!
