### ISSUE TITLE
"not possible to make backup without permission to write to the memory"

### ISSUE THREAD

**Issue by marc-medley** [nutritionfactsorg/daily-dozen-android#216]
@slavick for your review & comment ...

Observation below provided by @Lbouska from [Czech translation testing](https://github.com/nutritionfactsorg/daily-dozen-localization/issues/26#issuecomment-1335857012).

> only - backup tells: "It is not possible to make backup without permission to write to the memory." Hope those permissions will be asked during installation of the app. Normal people are not able to arrange this.

**Comment by slavick** [comment]
Closing this as Lbouska (the reporter of the bug) says it has been fixed: https://github.com/nutritionfactsorg/daily-dozen-localization/issues/26#issuecomment-1361040800
