### ISSUE TITLE
Serving Count and Search

### ISSUE THREAD

**Issue by Pantyhose-X** [nutritionfactsorg/daily-dozen-android#228]
### Insufficient nutrition, or excess can lead to disease
- [ ] Add statistics Children, Youth, Middle-aged, Elderly, Boxing, List the body's daily nutritional requirements.
[USDA lists 49 nutrients and dosages required by the human body](https://www.ars.usda.gov/ARSUserFiles/80400530/pdf/usual/Usual_Intake_gender_WWEIA_2013_2016.pdf)
- [ ]  Add Purchase quantity statistics.

Example
How much beef do I need to buy for my family of 1 child, 2 youths, and 1 elderly person, for a total of 4 people?

How much beef do I need to eat each day to meet my body's individual nutritional needs?
Example
![](https://www.beefresearch.ca/content/uploads/2022/04/Food_label_beef.jpg)

- [ ]  Add ingredient search.
When I clicked on vitamin A, the search listed foods high in vitamin A

---
This may exceed daily-dozen goals

**Comment by marc-medley** [comment]
> This may exceed daily-dozen goals

A nutrient database and related searchs are not part of the Daily Dozen application goals and design.

For more information on the scope and intent, please refer to ["The Daily Dozen Checklist: Frequently Asked Questions"](https://nutritionfacts.org/daily-dozen/).

> _" Rather than being a meal plan or diet in itself, it is simply a checklist to inspire you to include some of the healthiest foods in your diet."_

**Comment by marc-medley** [comment]
> This may exceed daily-dozen goals

A nutrient database and related searchs are not part of the Daily Dozen application goals and design.

For more information on the scope and intent, please refer to ["The Daily Dozen Checklist: Frequently Asked Questions"](https://nutritionfacts.org/daily-dozen/).

> _" Rather than being a meal plan or diet in itself, it is simply a checklist to inspire you to include some of the healthiest foods in your diet."_
