### ISSUE TITLE
Allow app to be moved to SD card 

### ISSUE THREAD

**Issue by mdh0312** [nutritionfactsorg/daily-dozen-android#25]
Currently this is not permitted. 

Samsung Prime Galaxy
Android 5.1.1

**Comment by MovGP0** [comment]
I don't think that this is important. The app only uses very little data and the SD card should be used for bulk data (videos, music, images, etc.) rather than applications. 

It's probably better to get rid of unused apps.

**Comment by mdh0312** [comment]
The SD card is not just for bulk data ... what happens when all the internal memory is used up?  I have moved much more complex apps (such as Firefox) to the SD card and they function just fine.  This is a poor design decision not to allow this app to be moved to the SD card.

**Comment by MovGP0** [comment]
@mdh0312 since this app makes use of the `android.app.AlarmManager` for daily notifications, moving to SD card might break those notifications. So when changing the `android:installLocation` to `auto`, it needs lots of additional testing.

**Comment by slavick** [comment]
This has been added in v12.2
