### ISSUE TITLE
Auto rotate based on device screen orientation

### ISSUE THREAD

**Issue by 72757373656c6c** [nutritionfactsorg/daily-dozen-android#257]
Feature request. 

I installed Daily Dozen from F-Droid on a Galaxy tablet with keyboard. Auto-rotate is enabled. I use the tablet horizontally (landscape). However, Daily Dozen only appears vertically (portrait). 

A user mentions this in issue #150.

> The app seems to ignore screen rotation. If I could rotate from portrait to landscape then there would be a lot more space to see the graph through time.

**Comment by slavick** [comment]
Closing this issue as the feature was added in [v27](https://github.com/nutritionfactsorg/daily-dozen-android/pull/256)
