### ISSUE TITLE
Swap images between Greens and Cruciferous Vegetables

### ISSUE THREAD

**Issue by christirichards** [nutritionfactsorg/daily-dozen-android#30]
The photo of the tablespoon of horseradish and sprouts should be in the cruciferous category.  They are currently listed under greens.

**Comment by myang310** [comment]
Hi Christi. May I work on this? This would be my first contribution to a OSS project.

**Comment by christirichards** [comment]
Absolutely!  If you have any issues or questions we can take it to email.  Please feel free to email me at christi@nutritionfacts.org.

**Comment by myang310** [comment]
I submitted the pull request! #31
:+1:
