### ISSUE TITLE
Translation management improvement

### ISSUE THREAD

**Issue by wywy22** [nutritionfactsorg/daily-dozen-android#37]
Thanks for adding the german language. I will work on the french translations using the value-de.xml template.
I have checked the IOS source code and it seems that the implementation of wording is quite different.
It would be good to find a way to harmonize translations files between both platforms. 

Why not use a phrase app or any other platform to have the translation approved ?

**Comment by vgstef** [comment]
Hi wywy22,
Do you need help for the French translation? I'm from Quebec and I really like to have this app available in French.
