### ISSUE TITLE
Add in the ability to toggle different units of measurements for categories

### ISSUE THREAD

**Issue by christirichards** [nutritionfactsorg/daily-dozen-android#4]
The current categories list servings in cups/spoons.  It has been highly requested that this information could be toggled to grams and (in the future) other units of measurement.

**Comment by jpritikin** [comment]
Cups/spoons would correspond to liters (a volume measure) not grams (a weight measure), but it would be nice to have both volume and weight.

**Comment by MovGP0** [comment]
since the measurements doesn't need to be precise, tha cups and spoons are useful for everyday use. 

the litres and kilograms measurements are useful for beginners who want to get a feel of how much that really is. so having both is probably a good idea. 

For the US based locale, there should also be measurements in anglo-american units. 

For Reference see [Wikipedia:Cooking weights and measures](https://en.wikipedia.org/wiki/Cooking_weights_and_measures).

**Comment by wywy22** [comment]
As user of metric system, it's hard to estimate the size of a cup or a glass. It would be good to have both infos displayed or the a option for choosing between both.

**Comment by MovGP0** [comment]
just figured that there is an additional problem with the spoon and cup sizes: in europe, we have cups and spoons of different sizes. the cups are 200 ml or 250 ml, and the spoons are much bigger.

**Comment by wywy22** [comment]
Moreover, the sizing is in the strings.xml. Not the best for translation

**Comment by MovGP0** [comment]
well, actually it is. however, the anglo american values should only be used in the "en-US" translation, while the default language, which is used in all the other countries, should use SI units.

**Comment by vgstef** [comment]
In Canada (en-CA and fr-CA), most people also use anglo american values.

**Comment by rggjan** [comment]
Also think it would be great to be able to switch!

**Comment by slavick** [comment]
I have been working on this, but I would love some help on actually converting the values to the metric system. Not being a user of the metric system, I'm not confident that I wouldn't make some glaring mistakes. Please let me know if you'd like to help.

Here's an early look at the UI for switching unit systems. Currently, it's a button that would switch to "metric" after you tap on it. Your most recent selection would be saved between app launches.

![unit switching ui](https://user-images.githubusercontent.com/410512/27298863-ea312762-54ef-11e7-9465-5a8d3bf75ab7.png)

**Comment by rggjan** [comment]
Cool, this would be perfect! I like the UI. Couldn't you just use chroot metric units from the book? For example:
![20170619_202243](https://user-images.githubusercontent.com/128554/27299670-6a80eb04-552d-11e7-8d82-9e0c3b27a9d3.png)

**Comment by slavick** [comment]
@rggjan If you have the time, can you send me screenshots of the serving sizes in your book? My book only has Imperial units. This would be great to put in the next update.

**Comment by rggjan** [comment]
@slavick of course! where should I send them to?

**Comment by slavick** [comment]
@rggjan I've sent you an email. Thank you very much!

**Comment by slavick** [comment]
This has been added in v13.
