### ISSUE TITLE
change the default language

### ISSUE THREAD

**Issue by gfvpelt** [nutritionfactsorg/daily-dozen-android#40]
Hi,

Could we add a feature to change away from the default language?
Think somewhere in hte menu where we can change the Daily Remender Settings could be a good place to do that?

I have translated the English Strings.xml file to dutch, however lot of people in the Netherlands have there mobile phone set to English. 

Some might even prefer the English daily dozen and have there phone to dutch

Thanks
GF

**Comment by VasileUngureanu** [comment]
Hi @gfvpelt 
In Android is a bad practice to make option to change local (only for current app) language from application. Its more like a hack rather than normal feature ))
