### ISSUE TITLE
Chickpeas and Garbanzo beans are the same in Greek

### ISSUE THREAD

**Issue by kapcom01** [nutritionfactsorg/daily-dozen-android#45]
In Greek we don't have two different words for this particular legume. We just have "Ρεβίθια". I have started translating the app and as of now I use the greek word twice as a solution.

What is the recommended way to handle this situation?
Thanks.

**Comment by slavick** [comment]
Please just duplicate the word for now. For the videos links to work, there must be the same number of foods in each translated list. I will refactor in the future to combine chickpeas and garbanzo beans in the same line.

Thanks

**Comment by alibitek** [comment]
They are the same thing. Some useful information I found while trying to understand why so:
- Etymology: 
   - https://en.wiktionary.org/wiki/garbanzo
  > From Spanish garbanzo (whence also calavance), possibly from Basque garau (“seed”) + antzu (“dry”). Another theory suggests an Ancient Greek origin, from ἐρέβινθος (erébinthos).  
    - https://en.wiktionary.org/wiki/chickpea
   > From French pois chiche, from pois (“pea”) + chiche, from Latin cicer (“chickpea”)

- [cooking.stackexchange.com - What is the difference between chickpeas and garbanzo beans?](https://cooking.stackexchange.com/questions/47748/what-is-the-difference-between-chickpeas-and-garbanzo-beans)
- [differencebetween.net - Difference Between Garbanzo Beans and Chickpeas](http://www.differencebetween.net/object/comparisons-of-food-items/processed-foods/difference-between-garbanzo-beans-and-chickpeas/)
- https://nutritionfacts.org/topics/garbanzo-beans/ vs https://nutritionfacts.org/topics/chickpeas/
