### ISSUE TITLE
Blackness on screen on a Galaxy S2 (app version 12.1)

### ISSUE THREAD

**Issue by AppleOatmeal** [nutritionfactsorg/daily-dozen-android#50]
Hi!

Today I installed the app again after I while, as I managed to clear around 1 GB of internal memory due to [this](https://www.theinternetpatrol.com/how-to-fix-out-of-space-insufficient-storage-problems-on-your-samsung-galaxy-s2/) little trick that blew my mind (my phone was absolutely clogged, couldn't install anything, many times not even update).

Anyway, so when I installed the app, it looked like this:
![screenshot_2017-06-05-17-19-44](https://cloud.githubusercontent.com/assets/22891293/26787956/8916c520-49c0-11e7-8e35-ade97f86c332.png)

There is that blackness. However, there isn't blackness anywhere else, just on the main screen.
Rest looks normal:
![screenshot_2017-06-05-17-30-53](https://cloud.githubusercontent.com/assets/22891293/26788170/33beb780-49c1-11e7-97f8-22cd239a77a0.png)
![screenshot_2017-06-05-17-31-40](https://cloud.githubusercontent.com/assets/22891293/26788169/33b6278c-49c1-11e7-999a-b922963ea339.png)
![screenshot_2017-06-05-17-31-55](https://cloud.githubusercontent.com/assets/22891293/26788168/33b5ae1a-49c1-11e7-9ff1-94edc0ed3d49.png)

I have tried reinstalling the app a few times, but that unfortunately didn't fix the issue.

I am using version 12.1 of the app on stock Android 4.1.2 (Galaxy S2). I'm happy to gather more information if needed to fix the issue. :) Thanks for making and maintaining the app!

**Comment by slavick** [comment]
This has been fixed in v12.2. Thanks for posting a screenshot of the bug and let me know if you find any more issues.
