### ISSUE TITLE
Add more cruciferous vegetables

### ISSUE THREAD

**Issue by dimqua** [nutritionfactsorg/daily-dozen-android#64]
Probably we should expand our [cruciferous vegetables](https://en.wikipedia.org/wiki/Cruciferous_vegetables) list with:

- [x] Savoy cabbage, Cone cabbage, Red cabbage;
- [x] Romanesco broccoli/cauliflower;
- [x] Colourful (green, purple, orange) cauliflower;
- [x] Kohlrabi;
- [ ] Mizuna;
- [ ] Napa cabbage;
- [ ] Broccolini and Rapini;
- [ ] Land cress and Garden cress.

Other suggestions are welcome!

**Comment by rahul577** [comment]
Should i add Savoy cabbage, Cone cabbage, Red cabbage with cabbage or should i add them all seperately.

**Comment by dimqua** [comment]
Cone cabbage can be green or red. I suggest to add something like:
```
Cabbage (green, red and savoy)
```

**Comment by alibitek** [comment]
Adding new cruciferous vegetables is good, but I think we also need to find and add some associated links to nutritionfacts.org that go along the recommendations, if possible.
