### ISSUE TITLE
Add Multiple Reminders

### ISSUE THREAD

**Issue by christirichards** [nutritionfactsorg/daily-dozen-android#84]
Users are requesting the ability to add multiple reminders so they can set them at different times/meals.  Right now, they have to go in and change their reminder time to reset the functionality they are looking for.

**Comment by paynemiller92** [comment]
I submitted a pull request for this issue! https://github.com/nutritionfactsorg/daily-dozen-android/pull/87

**Comment by miyalys** [comment]
...and I see, it has been merged in. So is the issue still open?

**Comment by inad9300** [comment]
Any news about this? (This level of responsiveness doesn't encourage new contributions very much!)

**Comment by slavick** [comment]
@inad9300 The PR was declined pending necessary changes; therefore, the issue has been left open.

**Comment by slavick** [comment]
This feature has been added in https://github.com/nutritionfactsorg/daily-dozen-android/pull/168
